### ISSUE TITLE
newbye to platform.io

### ISSUE THREAD

**Issue by croisez** [rossbeazley/SonoffBoilerplate#3]
hello, could you explain me the way to rebuild the sources?
I have installed (on osx) latest versions of Atom and Platform.io.
What should I do next: cmake? make?
I would like to rebuild the sources for esp01_1m environment.
Also, how to flash the HEX file after build?

**Comment by rossbeazley** [comment]
I actually use Microsoft Visual Code and thats quite different as it has a Tasks menu option where i can build or upload.

A quick look at the docs for atom/platformio suggests there is a PlatformIO in your menubar

http://docs.platformio.org/en/latest/ide/atom.html#menu-item-platformio

Building is command + alt + B
Uploading to your sonoff is command + alt + U


let me know if thats correct

**Comment by croisez** [comment]
Hello, thanks for your help.
I finally found a good tutorial here: https://projetsdiy.fr/bien-demarrer-platformio-ide-arduino-esp8266-esp32-stm32/
BTW, where were your sources forked from?

**Comment by rossbeazley** [comment]
The source repo is no longer available, its changed significantly since then
