### ISSUE TITLE
publish new status to mqtt broker does not makes relay to toggle

### ISSUE THREAD

**Issue by croisez** [rossbeazley/SonoffBoilerplate#4]
By using this command:
> mqtt_pub -h my.mosquitto.server -t "sonoff/sonoff/status" -m "on"

I was expecting the relay state to be toggled to ON.

The terminal says:
> sonoff/sonoff/status => pub not has_stream
topic: sonoff/sonoff/status
payload: on
for this device

I don't know if this is the expected behaviour

**Comment by beazlr02** [comment]
I would expect the command to look more like this 

`mqtt_pub -h my.mosquitto.server -t "topic/hostname" -m "on"`

where topic and hostname are what you supplied in the web portal

what version are you using?

ie when did you last pull from master?

**Comment by croisez** [comment]
ok, my mistake. the format of the topic was wrong. I tried it again, with the command as you mentioned, and now it works. Thanks for helping
